name: angular-app

on:
  push:
    branches: 
       - deployment
 
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps: 
    - name: trigger dsingle job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://192.168.1.128:8080"
        user: "kuldeep"
        token: ${{ TOKEN }}
        job: "deployment"
